feat: cleanTempDir
stryker-mutator/stryker pull request #2444
Opened 2020-08-29 13:39 UTC by kmdrGroch

fixes: #2435

2020-08-29 13:39 UTC, kmdrGroch commented
@nicojs something like this? 🤔

2020-08-29 15:34 UTC, nicojs requested changes
Seems good. One remark.

I've been thinking. Probably the best user experience is to leave the temp dir when an error occurred by default (our old behavior). For example, when `cleanTempDir` is true, only delete it when mutation testing was successful. 

To do this we would need to communicate the fact that an error occurred from `Stryker`'s `catch`. 

@kmdrGroch do you agree? If you need help, I could also implement this with a commit here.

2020-08-29 15:34 UTC, nicojs commented on packages/core/src/utils/TemporaryDirectory.ts
> +    this.removeDuringDisposal = options.cleanTempDir ?? true;
This `??` isn't needed right? Since it has a default value.

2020-08-29 17:03 UTC, kmdrGroch commented
Updated:
- now the functionality should be the same as it was before #2315 with a possibility to overwrite :)

2020-08-29 18:15 UTC, nicojs commented
I think the old behavior is still not there,. The `dispose` method of the `TemporaryDirectory` is called no matter what (error or no error), see https://github.com/stryker-mutator/stryker/blob/6885e16fad7699ba93e6ebbbf0755c7d98c50c5a/packages/core/src/Stryker.ts#L59.

2020-08-29 18:25 UTC, kmdrGroch commented
right! I am a dummy :D

2020-08-29 22:56 UTC, nicojs commented
>  If you want removing all disposes, i think what should be done is adding "enableDisposal" option or sth like this 🤔

No, we need to `dispose`, otherwise Stryker hangs forever 🙄. `dispose()` makes sure all child processes are closed and nodejs is allowed to exit.

What I meant was something like this:

Inside Stryker.ts

```ts
// 1. Prepare. Load Stryker configuration, load the input files and starts the logging server
      const prepareExecutor = loggerProvider.provideValue(coreTokens.cliOptions, this.cliOptions).injectClass(PrepareExecutor);
      const mutantInstrumenterInjector = await prepareExecutor.execute();

      try {
        // 2. Mutate and instrument the files and write to the sandbox.
        const mutantInstrumenter = mutantInstrumenterInjector.injectClass(MutantInstrumenterExecutor);
        const dryRunExecutorInjector = await mutantInstrumenter.execute();

        // 3. Perform a 'dry run' (initial test run). Runs the tests without active mutants and collects coverage.
        const dryRunExecutor = dryRunExecutorInjector.injectClass(DryRunExecutor);
        const mutationRunExecutorInjector = await dryRunExecutor.execute();

        // 4. Actual mutation testing. Will check every mutant and if valid run it in an available test runner.
        const mutationRunExecutor = mutationRunExecutorInjector.injectClass(MutationTestExecutor);
        const mutantResults = await mutationRunExecutor.execute();

        return mutantResults;
      } catch (error) {
       // Mark current run as failed, so tempoary directory can choose if it needs to clean or not.
        mutantInstrumenterInjector.resolve(coreTokens.temporaryDirectory).markRunErrored();
        throw error; // rethrow
      }
```

2020-09-03 09:56 UTC, nicojs commented
Is this clear @kmdrGroch ? I don't see another way, other than adding a parameter to the `dispose` and alter `typed-inject` to accomondate this. Not sure yet if I would want to add that.

2020-09-03 12:03 UTC, kmdrGroch commented
I don't quite get it 😕

2020-09-17 17:30 UTC, nicojs commented
I had some time, so implemented it.

What I did:

* Made sure to only clean the temp dir when Stryker succesfully executed (it's quite simple, please have a look 👍)
    ```ts
    catch (error) {
      const log = loggerProvider.resolve(commonTokens.getLogger)(Stryker.name);
      log.debug('Not removing the temp dir because an error occurred');
      mutantInstrumenterInjector.resolve(coreTokens.temporaryDirectory).removeDuringDisposal = false;
      throw error;
    }      
    ```
* Made `true` the default value (so after a succesful run, the `.stryker-tmp` dir is gone.
* I've added `--cleanTempDir` as a cli option
* I've documented it in the readme.md

2020-09-17 18:03 UTC, nicojs approved these changes

2020-09-17 18:26 UTC, merged